### ISSUE TITLE
get "function definition is void: interactive-call" error when counsel-gtags-dwim is executed

### ISSUE THREAD

**Issue by hexingb** [FelipeLema/emacs-counsel-gtags#20]
Hello.

My counsel-tags configuration is like this:

`(use-package counsel-gtags
  :ensure t
  :delight
  :commands counsel-gtags-mode
  :bind (:map
         counsel-gtags-mode-map
         ("M-." . counsel-gtags-dwim)
         ("M-," . counsel-gtags-go-backward))
  :hook ((swift-mode . counsel-gtags-mode)
         (swift-mode . ggtags-mode)))`

OS: Debian GNU/Linux 10 (buster)
emacs version: 26.1
counsel-tags version: counsel-gtags-20201102.2116

When I execute counsel-gtags-dwin, after pressing 'y' for a new GTAGS file creation, "Symbol’s function definition is void: interactive-call" is reported. I find "interactive-call" in counsel-tags.el at line 464, but have no idea of what it is. I'm sorry for my ignorance about emacs lisp, but could you please point me how to fix it?

**Comment by FelipeLema** [comment]
Thanks for reporting this.

Please, confirm (or re-open if it isn't fixed) on your side

**Comment by hexingb** [comment]
Thanks for your timely fix.
