### ISSUE TITLE
Issue in global-tags

### ISSUE THREAD

**Issue by Ergus** [FelipeLema/emacs-counsel-gtags#23]
Hi Felipe:

Sorry for reporting here, but I don't know how to report issues in the other page (I really didn't tried too much either).

The latest changes in global-tags created some issues in my system. Checking the code I see the variable `global-tags-exclusive-backend-mode` in the `global-tags-shared-backend-mode` so the shared mode is broken because it never becomes enabled and I get this:

![image](https://user-images.githubusercontent.com/6975176/101027123-04559f80-3578-11eb-9e39-9dd5a111765c.png)

**Comment by FelipeLema** [comment]
as long as the message gets through... I don't mind

I just uploaded a fix... keep an eye out for melpa update

**Comment by Ergus** [comment]
BTW when loading the package I get this two warnings:

```
global-tags.el: ‘project-roots’ is an obsolete generic function (as of 0.3.0); use ‘project-root’ instead.
Eager macro-expansion failure: (error "Attempting to set a non-symbol: 'xref-backend-functions")
```

They are very simple to fix, just use the other function and remove the quote in `(setq-local 'xref-backend-functions`

Also in the `remove-hook` calls like:

```
(remove-hook 'xref-backend-functions 'xref-backend-functions)
```

I don't think are fine.

Best,
Ergus

**Comment by FelipeLema** [comment]
my bad. just uploaded a fix for this.

**Comment by Ergus** [comment]
Hi Felipe:

The package is much better now. Maybe it may be interesting to add it to Elpa or the new non-gnu Elpa repositories to improve visibility for those users not using Melpa. As you are the only contributor it may be simple to do; because usually the complicated part is to gather the copyright assignment for all contributors.
