### ISSUE TITLE
Old link in packages-list

### ISSUE THREAD

**Issue by Ergus** [FelipeLema/emacs-counsel-gtags#7]
Hi Felipe:
I have seen that in packages-list in elpa they transferred the download repo to you, but the link shown is still the old one from syohex.

So there is some activity (an issue on June 24) and no reply.

**Comment by xuhdev** [comment]
Which link are you referring to? I saw all relevant links point to this repo at https://melpa.org/#/counsel-gtags

**Comment by Ergus** [comment]
I mean in the package documentation of package-list-packages.

![image](https://user-images.githubusercontent.com/6975176/64488865-f027d300-d24c-11e9-9afa-90f152e8931d.png)
