### ISSUE TITLE
find_tag_other_window?

### ISSUE THREAD

**Issue by Ergus** [FelipeLema/emacs-counsel-gtags#9]
Hi, do you think it makes sense to add find-other-window like behavior when called with universal prefix for example??

It shouldn't be so complex right? And with a change in counsel-gtags--jump-to it could benefit all the commands.

**Comment by FelipeLema** [comment]
Sounds like very usable. I'll be working on it, but it might take a few days (I know it _can_ be done, but I don't know the exact commands)... you might get the Pull Request for it ready before I do.

**Comment by Ergus** [comment]
Hi Felipe:

I can't try this now. But I think ivy defines ivy-current-prefix-arg as a global variable.  And the command to open in other window is find-file-other-window... Any way if I have some time this week I'll try to do it.
